config/routes.rb
Pcs::Application.routes.draw do
  resources :users do
    resources :characters
  end
  resources :sessions, only: [:new, :create, :destroy]
  root  'static_pages#home'
  match '/signup',  to: 'users#new',          via: 'get'
  match '/signin',  to: 'sessions#new',       via: 'get'
  match '/signout', to: 'sessions#destroy',   via: 'delete'
  match '/help',    to: 'static_pages#help',  via: 'get'
  match '/about',   to: 'static_pages#about', via: 'get'

  

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :characters, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :slug, uniqueness: true, presence: true
  before_validation :generate_slug 
  before_create :create_remember_token
  validates :name, presence: true, length: { minimum: 5, maximum: 50 },
                   uniqueness: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def to_param
    slug
  end

  def generate_slug
    self.slug ||= name.parameterize
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end
  
  def show
    @user = User.find_by_slug!(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Pathfinder Character Sheet App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    def user
      @user ||= User.find_by_slug!(params[:id])
    end
    helper_method :user
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.haml
- provide(:title, "Sign up")
%h1 Sign up

.row
  .col-md-6.col-md-offset-3
    = form_for(@user) do |f|
      = render 'shared/error_messages'

      = f.label :name
      = f.text_field :name

      = f.label :email
      = f.text_field :email
      
      = f.label :password
      = f.password_field :password

      = f.label :password_confirmation, "Confirmation"
      = f.password_field :password_confirmation

      = f.submit "Create my account", class: "btn btn-large btn-primary"

app/views/users/show.html.haml
- provide(:title, @user.name)
.row
  .col-xs-4
    %section
      %h1= @user.name

  .col-xs-8
    - if @user.characters.empty?
      %h2 
        You don't have any characters yet!
    - else
      - @user.characters.each do |character|
        .row
          .col-xs-2
            = character.name
          .col-xs-8
            %ul
              -# character.classes.each do |key, value|
                %li
                  -#"#{key.to_s.humanize.titleize}: #{value}"
                  = "#{character.classes.humanize.titleize}"
          .col-xs-2
            = link_to 'Edit', edit_user_character_path(@user, character.id)
    = link_to "Create a new character", new_user_character_path(@user), 
      class: "btn btn-large btn-primary"