config/routes.rb
Pcs::Application.routes.draw do
  resources :users do
    resources :characters
  end
  resources :sessions, only: [:new, :create, :destroy]
  root  'static_pages#home'
  match '/signup',  to: 'users#new',          via: 'get'
  match '/signin',  to: 'sessions#new',       via: 'get'
  match '/signout', to: 'sessions#destroy',   via: 'delete'
  match '/help',    to: 'static_pages#help',  via: 'get'
  match '/about',   to: 'static_pages#about', via: 'get'

  

end

app/views/layouts/_footer.html.haml
%footer.footer

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container
      %nav
        %ul.nav.pull-right
          %li= link_to "Home",    root_path
          %li= link_to "Help",    help_path
          %li= link_to "About",   about_path
          - if signed_in?
            %li#fat-menu.dropdown
              %a.dropdown-toggle(href="#" data-toggle="dropdown")
                Account
                %b.caret
              %ul.dropdown-menu
                %li= link_to "Profile", current_user
                %li= link_to "Settings", '#'
                %li.divider
                %li= link_to "Sign out", signout_path, method: "delete"
          - else
            %li= link_to "Sign in", signin_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= full_title(yield(:title))
    = stylesheet_link_tag    "application", media: "all", 
                                            "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true 
    = csrf_meta_tags
    /[if lt IE 9]%script{:src => "http://html5shim.googlecode.com/svn/trunk/html5.js"}
    %meta{name: "viewport", content: "width=device-width, initial-scale=1"}
  %body
    = render 'layouts/header'
    .container
      - flash.each do |key, value|
        %div{:class => ["alert", "alert-#{key}"]}= value
      = yield
    = render 'layouts/footer'
    = debug(params) if Rails.env.development?